version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: cimg/node:14.0.0
    steps:
    - checkout
    - run:
        name: Install Dependencies
        command: yarn install
    - run:
        name: Compile
        command: yarn prepack