version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: cimg/node:14.0.0
    steps:
    - run:
        name: Install Dependencies
        command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
    - run:
        name: Compile
        command: yarn prepack